/* Felt Ledger hosted service worker (generated by vite.config.ts → dist-hosted/sw.js; see docs/hosted.md).
 * - App shell + hashed assets: precached at install, served cache-first (so the Home Screen app opens offline).
 * - Pages (navigations): network first (3.5 s), falling back to the cached index.html.
 * - ./data/ (the encrypted hand pool) and any URL with a query string: straight to the network, never cached here;
 *   the app keeps its own decrypted copy in IndexedDB.
 */
const VERSION = 'cd0dd8bba2e6';
const ASSETS = [
  "./",
  "./apple-touch-icon-precomposed.png",
  "./apple-touch-icon.png",
  "./assets/charts-Doc3xU3k.js",
  "./assets/index-DtFQwTxa.js",
  "./assets/index-Zo_5enw-.css",
  "./assets/react-l0sNRNKZ.js",
  "./assets/router-DTv_Xs5V.js",
  "./favicon.ico",
  "./favicon.svg",
  "./icon-192.png",
  "./icon-512.png",
  "./index.html",
  "./manifest.webmanifest"
];
const CACHE = 'felt-ledger-shell-' + VERSION;
const SCOPE = new URL('./', self.location.href);
const INDEX = new URL('./index.html', SCOPE).href;

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((c) => c.addAll(ASSETS.map((a) => new Request(new URL(a, SCOPE).href, { cache: 'reload' }))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('felt-ledger-shell-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

function timeout(ms) {
  return new Promise((_, reject) => setTimeout(() => reject(new Error('timeout')), ms));
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== SCOPE.origin || !url.pathname.startsWith(SCOPE.pathname)) return;
  if (url.pathname.startsWith(SCOPE.pathname + 'data/')) return;

  if (req.mode === 'navigate') {
    event.respondWith(
      (async () => {
        const cache = await caches.open(CACHE);
        try {
          const res = await Promise.race([fetch(INDEX, { cache: 'no-cache' }), timeout(3500)]);
          if (res && res.ok) {
            await cache.put(INDEX, res.clone());
            return res;
          }
        } catch (e) {
          /* offline or slow: use the cached shell */
        }
        return (await cache.match(INDEX)) || fetch(req);
      })(),
    );
    return;
  }
  if (url.search) return; // e.g. the update check's index.html?v=…

  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);
      const hit = await cache.match(req);
      if (hit) return hit;
      const res = await fetch(req);
      if (res.ok && res.type === 'basic') cache.put(req, res.clone()).catch(() => undefined);
      return res;
    })(),
  );
});
